### ISSUE TITLE
Inverting forwards/backwards controls

### ISSUE THREAD

**Issue by N1cknamed** [moehreag/realistic-rowing#3]
Currently boats maintain their vanilla controls, pressing the forwards key to move the boat forwards (duh). However that means that from the players' new perspective you need to press forwards to travel backwards, which feels rather unintuitive. It would be nice to invert these controls whenever the player is in a boat.

I recognize that many players will probably switch to F5 selfie mode to get a fairly vanilla view, so this should probably be a configurable option.

Ideal solution would be to maintain logical directional controls for each perspective (inverted in first person, normal in selfie mode) but that may be out of scope for what is already a very niche mod.

**Comment by moehreag** [comment]
it is actually rather simple to check for the perspective of the camera and invert the controls if the game is in first-person mode (and the player is in a boat), though this may be just as unintuitive to use as it might get confusing when the controls switch together with the perspective.

**Comment by N1cknamed** [comment]
The implementation is incorrect, you need to check for isFrontView() instead of isFirstPerson(). With that adjustment it works flawlessly.

After trying it out myself I do however agree with you that switching controls based on perspective might not be the best way to go about it, and it'd be inconsistent with normal walking in 3P. Maybe better to just do a flat invert regardless of perspective.

I'd still vouch for a config option. You could support all scenarios that way (normal/inverted/perspective-based).
