### ISSUE TITLE
Full lookaround while the boat is stationary

### ISSUE THREAD

**Issue by N1cknamed** [moehreag/realistic-rowing#4]
No explanation needed really, let the player completely turn around while they're not moving. Makes the mod a little more comfortable to use while keeping it realistic.

Would need to consider a way to smoothly snap the camera back if the player starts moving again from an 'illegal' angle.

Love the mod by the way, as a rower myself. Maybe if I can get a little more versed on Minecraft modding I'll try to contribute some enhancements myself.

**Comment by moehreag** [comment]
If you don't mind, could you test whether the implementation matches your ideas (of both issues you opened)? If you need help, either just ask here or [join the discord](https://discord.gg/BfmYmPw3Ts).

**Comment by N1cknamed** [comment]
That was fast. I tried it out, the ability to look around seems to work well, but the camera snap when you get moving is a little jarring. If that could instead be a smooth interpolation (something like Minecarts used to do on turns) it would be perfect. But it is already a very welcome improvement.
