### ISSUE TITLE
Compatibility with HorseInBoat mod

### ISSUE THREAD

**Issue by Fyoncle** [moehreag/realistic-rowing#6]

**Comment by moehreag** [comment]
Would you mind to expand on:
- What the exact compatibility issue is (e.g. crash log, screenshot of issue, ..)
- What (in your opinion) a possible solution to the issue would be

Thank you.

**Comment by Fyoncle** [comment]
> Would you mind to expand on:
> 
> * What the exact compatibility issue is (e.g. crash log, screenshot of issue, ..)
> * What (in your opinion) a possible solution to the issue would be
> 
> Thank you.

It just kicks the horse out when you enter the boat, a possible solution would be just not kicking it at all xD

**Comment by moehreag** [comment]
This mod doesn't touch the code used for entities to enter a boat so this is weird. Which game version are you using currently?

**Comment by Fyoncle** [comment]
> This mod doesn't touch the code used for entities to enter a boat so this is weird. Which game version are you using currently?

1.20.1 Fabric

**Comment by moehreag** [comment]
I'm sorry, I'm not experiencing this issue (using only this mod and HorseInBoat, on 1.20.1)

<details><summary>Screenshot of player and horse in boat, with the player visibly being turned around by this mod</summary>
<p>


![2024-11-24_23 30 00](https://github.com/user-attachments/assets/bd2db671-7a78-431a-aea6-0722ab5a6a8a)

</p>
</details>

**Comment by Fyoncle** [comment]
> I'm sorry, I'm not experiencing this issue (using only this mod and HorseInBoat, on 1.20.1)
> 
> Screenshot of player and horse in boat, with the player visibly being turned around by this mod
> 
> ![2024-11-24_23 30 00](https://private-user-images.githubusercontent.com/85403855/389314396-bd2db671-7a78-431a-aea6-0722ab5a6a8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0ODc5MzMsIm5iZiI6MTczMjQ4NzYzMywicGF0aCI6Ii84NTQwMzg1NS8zODkzMTQzOTYtYmQyZGI2NzEtN2E3OC00MzFhLWFlYTYtMDcyMmFiNWE2YThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDIyMzM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NDEwODM0ZDhmODc2N2ZhNzFiM2JmODVhNzU0YTNmZWZiNWJiNTUwNDNkYjgyNzk0YWMxOGI2NTIyNmQ5NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mlE7zXQu6CkYBSEdfyumvnKWg_hOoyb7L9GBntoUq_0)

Could you try with the modpack Elysium Days, and 6.0.0 version of it

**Comment by moehreag** [comment]
Unfortunately I'm not able to try to figure out the issue further since your modpack crashes in dubious ways:
- Crash 1: <https://mclo.gs/hDhV0bK> (Crash because setting the window icon is unsupported on wayland) 
  - Mitigated by replacing the `CustomIcon` class inside `elysium-days-tweaks` with a no-op. This class does not seem to be present in the sources published at <https://github.com/Fyoncle/ElysiumDaysTweaks> and the current implementation shouldn't have this issue as it does not call GLFW on its own (Minecraft checks on its own and doesn't set the window icon if wayland is detected)
- Crash 2: <https://mclo.gs/hDhV0bK> 
  - jvm error: <https://mclo.gs/apCgcb9> 
    With this error I have no idea what could cause it.

**Comment by Fyoncle** [comment]
> Unfortunately I'm not able to try to figure out the issue further since your modpack crashes in dubious ways:
> 
> * Crash 1: https://mclo.gs/hDhV0bK (Crash because setting the window icon is unsupported on wayland)
>   
>   * Mitigated by replacing the `CustomIcon` class inside `elysium-days-tweaks` with a no-op. This class does not seem to be present in the sources published at https://github.com/Fyoncle/ElysiumDaysTweaks and the current implementation shouldn't have this issue as it does not call GLFW on its own (Minecraft checks on its own and doesn't set the window icon if wayland is detected)
> * Crash 2: https://mclo.gs/hDhV0bK
>   
>   * jvm error: https://mclo.gs/apCgcb9
>     With this error I have no idea what could cause it.

Crash 1 already fixed in the repo and will be fixed with 7.0.0 of Elysium Days but not sure what u talking about with the Crash 2, thank you for investigating the modpack further.

And i think i was just accidentaly pressed Shift + Right Click with Dismount Entity, which shouldnt make me sit on the boat but i'm unsure. I'll try again and tell you how its gone

**Comment by Fyoncle** [comment]
Yeah it was me being dumb with bumping shift accidentally, i'm so sorry!
